FROM ubuntu:24.04
MAINTAINER spadacciniweb spadacciniwev@gmail.com
USER root

RUN apt-get -y update && \
    apt-get -y upgrade && \
    echo -n "Africa/Lusaka" > /etc/timezone && \
    apt-get -y install make libconfig-tiny-perl libfile-slurp-perl liblist-allutils-perl libtext-asciitable-perl python3 cargo cargo-1.85 && \
    rm -rf /var/lib/apt/lists/* && \
    echo "Container is ready to go!!"

ADD scripts /opt/bench
WORKDIR /opt/bench

# CMD ["/bin/bash"]
CMD ["sleep", "infinity"]
