FROM ubuntu:24.04
MAINTAINER spadacciniweb spadacciniwev@gmail.com
USER root

RUN apt-get -y update && \
    apt-get -y upgrade && \
    echo -n "Europe/Rome" > /etc/timezone && \
    apt-get -y install make libconfig-tiny-perl libfile-slurp-perl liblist-allutils-perl libtext-asciitable-perl python3 cargo cargo-1.85 golang-go golang-gopkg-ini.v1-dev && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /root/go && \
    ln -s /usr/share/gocode/src /root/go/src && \
    go env -w GO111MODULE=auto && \
    echo "The image is ready, now container is ready to go!!"

ADD scripts /opt/bench
WORKDIR /opt/bench

# CMD ["/bin/bash"]
CMD ["sleep", "infinity"]
