all:
	@echo "\n# run increment..." | tee output_python.log && python3 increment.py | tee -a output_python.log
	@echo "\n# run encode_base64..." | tee -a output_python.log && python3 encode_base64.py | tee -a output_python.log
	@echo "\n# run digest..." | tee -a output_python.log && python3 digest.py | tee -a output_python.log

