all:
	@echo "\n# run greeting..." | tee output_perl.log && perl greeting.pl | tee -a output_perl.log
	@echo "\n# run increment..." | tee -a output_perl.log && perl increment.pl | tee -a output_perl.log
	@echo "\n# run encode_base64..." | tee -a output_perl.log && perl encode_base64.pl | tee -a output_perl.log
	@echo "\n# run digest..." | tee -a output_perl.log && perl digest.pl | tee -a output_perl.log

