all:
	@echo "# run increment..." | tee output_python.log && python3 increment.py | tee -a output_python.log
	@echo "# run encode_base64..." | tee -a output_python.log && python3 encode_base64.py | tee -a output_python.log
	@echo "# run digest..." | tee -a output_python.log && python3 digest.py | tee -a output_python.log

