all:
	@echo "# run increment..." | tee output_perl.log && perl increment.pl | tee -a output_perl.log
	@echo "# run encode_base64..." | tee -a output_perl.log && perl encode_base64.pl | tee -a output_perl.log
	@echo "# run digest..." | tee -a output_perl.log && perl digest.pl | tee -a output_perl.log

