all:
	@echo "# run increment..." | tee output_go.log && go run increment.go | tee -a output_go.log
	@echo "# run encode_base64..." | tee -a output_go.log && go run encode_base64.go | tee -a output_go.log
