all:
	@echo "\n# run increment..." | tee output_go.log && go run increment.go | tee -a output_go.log
	@echo "\n# run encode_base64..." | tee -a output_go.log && go run encode_base64.go | tee -a output_go.log
	@echo "\n# run digest..." | tee -a output_go.log && go run digest.go | tee -a output_go.log
